# Initialization

atom_style      full
boundary        p p p
dimension       3
newton          on
units           real

# Atom definition

read_data       data.lammps

# Force fields

pair_style      lj/cut/coul/long 9.0
pair_coeff      2 2 0.1553 3.166 # O-O,from lammps doc
pair_coeff      1 1 0.0 0.0 # H-H
pair_coeff      1 2 0.0 0.0 # O-H
kspace_style    pppm 1.0e-4

bond_style      harmonic
bond_coeff      1 450.0 1.0
angle_style     harmonic
angle_coeff     1 100.0 109.47

# Settings

neighbor        2.0 bin
run_style       verlet
timestep        1.0
velocity        all create 298.0 1993 dist gaussian

fix             1 all shake 0.0001 20 1000 b 1 a 1
fix             2 all nvt temp 298.0 298.0 100.0

# Compute and store local pressure tensor variation in x

compute		1 all stress/atom NULL
fix 		3 all ave/spatial 100 900 100000 x lower 0.317 c_1[1] c_1[2] c_1[3] units box norm all ave running file stress.dat overwrite

# Output

thermo          100

dump            myDump all atom 100 dump.atom
dump            myxyz all xyz 100 dump.xyz

# Actions

run             1000000
